language: go
sudo: false
go:
  - 1.10.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/apk-file-darwin-amd64
          - cross/apk-file-darwin-amd64.md5
          - cross/apk-file-darwin-amd64.sha256
          - cross/apk-file-darwin-386
          - cross/apk-file-darwin-386.md5
          - cross/apk-file-darwin-386.sha256
          - cross/apk-file-freebsd-amd64
          - cross/apk-file-freebsd-amd64.md5
          - cross/apk-file-freebsd-amd64.sha256
          - cross/apk-file-freebsd-386
          - cross/apk-file-freebsd-386.md5
          - cross/apk-file-freebsd-386.sha256
          - cross/apk-file-linux-arm
          - cross/apk-file-linux-arm.md5
          - cross/apk-file-linux-arm.sha256
          - cross/apk-file-linux-arm64
          - cross/apk-file-linux-arm64.md5
          - cross/apk-file-linux-arm64.sha256
          - cross/apk-file-linux-amd64
          - cross/apk-file-linux-amd64.md5
          - cross/apk-file-linux-amd64.sha256
          - cross/apk-file-linux-386
          - cross/apk-file-linux-386.md5
          - cross/apk-file-linux-386.sha256
          - cross/apk-file-solaris-amd64
          - cross/apk-file-solaris-amd64.md5
          - cross/apk-file-solaris-amd64.sha256
          - cross/apk-file-windows-amd64
          - cross/apk-file-windows-amd64.md5
          - cross/apk-file-windows-amd64.sha256
          - cross/apk-file-windows-386
          - cross/apk-file-windows-386.md5
          - cross/apk-file-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "Yf3XI7nLyfbd/KLv3trryW+HaXpEsRHpD/5dCFDyBWbsOarGgvXVw8vB470vkxia6aywOUztRM/dV2W3VcpISgaCKQUuvYSA9zV1tUDiwlHCKvoRRhEo1cJe9fgUX4MZpuh/3gSSh3Ja5xg1U83pCQpufryGCJb2hN08rbkcftQKZh4LQy1fB4luzXuk1MgQ4RP0r7sM1pep2xcG9QlB8wKEVilWOBSjMhtV4ybX5s8WsqSGx5z/Cywg+pAS+VpfdPhVQ3mElDYkr3dbFqQk2Zeh/0nxfV+6VVg7mY75lq+uahBMJS1mMTFpdCx66vEWi6Tif1SAGjCWeJVi33/0/CL9Lv9AHivd/8ElWEnA3yQjnvYZwGktm2EKQw/9HA4lPZsKjOwb0DKeSz3aWUIsTt2/lmEoECAxWfyrIv0l3b7FhWCq+ILpN/Da6GoWm8zGZMFZ5urJRiLxnvf/GUo8PWIHIqHa8iUSEl6xcFswtz0C/PX1g8thuKbB/zAzw/v32bYd71MR23BZIxkODlG6sUgTqRWnOcheYGGpHOZZp6bXJ02GmGks07+1HZVojMo5P+CAKvANjHNdf/sSg/TCZcWjrjqH6HivYCJNz8YmC6yigeWqk4aO9Fww4Nk6wSdo+Jsc6Il/0BwBkNvi2vRiVZtWHKfvy4RQ26iaFR2/gV4="
